apiVersion: 1
datasources:
  - name: Lido Prometheus
    uid: lido-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9092
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: POST
